name: Metrics-Readme
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      # Markdown output
      - uses: lowlighter/metrics@latest
        with:
          # ... other options
#           isocalendar: yes
#           languages: yes
          template: markdown
          filename: README.md         # Output file
          markdown: TEMPLATE.md       # Template file
          markdown_cache: .cache      # Cache folder
          token: ${{ secrets.METRICS_TOKEN }}
