name: Metrics-Readme
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      # Markdown output
      - uses: lowlighter/metrics@latest
        with:
          template: markdown
          filename: README.md         # Output file
          markdown: TEMPLATE.md       # Template file
          config_output: markdown
          config_timezone: Asia/Shanghai
          topics: yes
          achievements: yes
          plugin_topics: yes
          plugin_topics_limit: 24
          plugin_achievements: yes
          plugin_achievements_limit: 5
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          # ... other options
#           isocalendar: yes
#           languages: yes
          markdown_cache: .cache      # Cache folder
          token: ${{ secrets.METRICS_TOKEN }}
